; vectors.s - generated by vectors.py
; Michael Lazear 2016-2017, adapted from xv6-public

global vectors
global trap_handler
extern outb 

extern trap 

trap_handler:
	cli 
	push r15
	push r14
	push r13 
	push r12 
	push r11 
	push r10 
	push r9
	push r8
	push rdi 
	push rsi 
	push rbp 
	; no rsp push
	push rbx 
	push rdx 
	push rcx 
	push rax 

	mov rdi, rsp 
	call trap

	pop rax 
	pop rcx 
	pop rdx 
	pop rbx
	; no rsp pop 
	pop rbp
	pop rsi 
	pop rdi
	pop r8
	pop r9 
	pop r10 
	pop r11 
	pop r12 
	pop r13
	pop r14
	pop r15

	;mov al, 0x20 
	;out 0x20, al

	; We push 2 values in each vector, pop them off
	add rsp, 16
	iretq

global syscall_entry
global sysret_entry

; Stack pointers for SYSCALL/SYSRET are not specified through model specific registers. The clearing of bits in
; RFLAGS is programmable rather than fixed. SYSCALL/SYSRET save and restore the RFLAGS register.
; For SYSCALL, the processor saves RFLAGS into R11 and the RIP of the next instruction into RCX; it then gets the
; privilege-level 0 target code segment, instruction pointer, stack segment, and flags as follows:
; • Target code segment — Reads a non-NULL selector from IA32_STAR[47:32].
; • Target instruction pointer — Reads a 64-bit address from IA32_LSTAR. (The WRMSR instruction ensures
; that the value of the IA32_LSTAR MSR is canonical.)
; • Stack segment — Computed by adding 8 to the value in IA32_STAR[47:32].
; • Flags — The processor sets

; setjmp:
; 	pop rsi 				; rip is at top of stack 
; 	xor rax, rax 			; return value
; 	mov [rdi+0x00], rbx 
; 	mov [rdi+0x08], rsp		; Post-return rsp
; 	push rsi 				; Realign stack 
; 	mov [rdi+0x10], rbp 
; 	mov [rdi+0x18], r12 
; 	mov [rdi+0x20], r13 
; 	mov [rdi+0x28], r14 
; 	mov [rdi+0x30], r15
; 	mov [rdi+0x38], rsi 	; rip

; 	ret 
extern syscall_handler
syscall_entry:
	push rsp
	push r15
	push r14
	push r13 
	push r12 
	push rbp 
	push rbx 
	push r11 	; rflags
	push rcx 	; return address 
	push rdx
	push rsi 
	push rdi 
	push rax 	; syscall number 
	mov rdi, rsp
	call syscall_handler



; When SYSRET transfers control to 64-bit mode user code using REX.W, the processor gets the privilege level 3
; target code segment, instruction pointer, stack segment, and flags as follows:
; • Target code segment — Reads a non-NULL selector from IA32_STAR[63:48] + 16.
; • Target instruction pointer — Copies the value in RCX into RIP.
; • Stack segment — IA32_STAR[63:48] + 8.
; • EFLAGS — Loaded from R11.

sysret_entry:
	pop rax 
	pop rdi
	pop rsi 
	pop rdx
	pop rcx 
	pop r11 
	pop rbx 
	pop rbp
	pop r12 
	pop r13 
	pop r14 
	pop r15 
	pop rsp

	jmp rcx
	hlt
	sysret

vector0:
	push 0
	push 0
	jmp trap_handler
vector1:
	push 0
	push 1
	jmp trap_handler
vector2:
	push 0
	push 2
	jmp trap_handler
vector3:
	push 0
	push 3
	jmp trap_handler
vector4:
	push 0
	push 4
	jmp trap_handler
vector5:
	push 0
	push 5
	jmp trap_handler
vector6:
	push 0
	push 6
	jmp trap_handler
vector7:
	push 0
	push 7
	jmp trap_handler
vector8:
	push 8
	jmp trap_handler
vector9:
	push 0
	push 9
	jmp trap_handler
vector10:
	push 10
	jmp trap_handler
vector11:
	push 11
	jmp trap_handler
vector12:
	push 12
	jmp trap_handler
vector13:
	push 13
	jmp trap_handler
vector14:
	push 14
	jmp trap_handler
vector15:
	push 0
	push 15
	jmp trap_handler
vector16:
	push 16
	jmp trap_handler
vector17:
	push 0
	push 17
	jmp trap_handler
vector18:
	push 0
	push 18
	jmp trap_handler
vector19:
	push 0
	push 19
	jmp trap_handler
vector20:
	push 0
	push 20
	jmp trap_handler
vector21:
	push 0
	push 21
	jmp trap_handler
vector22:
	push 0
	push 22
	jmp trap_handler
vector23:
	push 0
	push 23
	jmp trap_handler
vector24:
	push 0
	push 24
	jmp trap_handler
vector25:
	push 0
	push 25
	jmp trap_handler
vector26:
	push 0
	push 26
	jmp trap_handler
vector27:
	push 0
	push 27
	jmp trap_handler
vector28:
	push 0
	push 28
	jmp trap_handler
vector29:
	push 0
	push 29
	jmp trap_handler
vector30:
	push 0
	push 30
	jmp trap_handler
vector31:
	push 0
	push 31
	jmp trap_handler
vector32:
	push 0
	push 32
	jmp trap_handler
vector33:
	push 0
	push 33
	jmp trap_handler
vector34:
	push 0
	push 34
	jmp trap_handler
vector35:
	push 0
	push 35
	jmp trap_handler
vector36:
	push 0
	push 36
	jmp trap_handler
vector37:
	push 0
	push 37
	jmp trap_handler
vector38:
	push 0
	push 38
	jmp trap_handler
vector39:
	push 0
	push 39
	jmp trap_handler
vector40:
	push 0
	push 40
	jmp trap_handler
vector41:
	push 0
	push 41
	jmp trap_handler
vector42:
	push 0
	push 42
	jmp trap_handler
vector43:
	push 0
	push 43
	jmp trap_handler
vector44:
	push 0
	push 44
	jmp trap_handler
vector45:
	push 0
	push 45
	jmp trap_handler
vector46:
	push 0
	push 46
	jmp trap_handler
vector47:
	push 0
	push 47
	jmp trap_handler
vector48:
	push 0
	push 48
	jmp trap_handler
vector49:
	push 0
	push 49
	jmp trap_handler
vector50:
	push 0
	push 50
	jmp trap_handler
vector51:
	push 0
	push 51
	jmp trap_handler
vector52:
	push 0
	push 52
	jmp trap_handler
vector53:
	push 0
	push 53
	jmp trap_handler
vector54:
	push 0
	push 54
	jmp trap_handler
vector55:
	push 0
	push 55
	jmp trap_handler
vector56:
	push 0
	push 56
	jmp trap_handler
vector57:
	push 0
	push 57
	jmp trap_handler
vector58:
	push 0
	push 58
	jmp trap_handler
vector59:
	push 0
	push 59
	jmp trap_handler
vector60:
	push 0
	push 60
	jmp trap_handler
vector61:
	push 0
	push 61
	jmp trap_handler
vector62:
	push 0
	push 62
	jmp trap_handler
vector63:
	push 0
	push 63
	jmp trap_handler
vector64:
	push 0
	push 64
	jmp trap_handler
vector65:
	push 0
	push 65
	jmp trap_handler
vector66:
	push 0
	push 66
	jmp trap_handler
vector67:
	push 0
	push 67
	jmp trap_handler
vector68:
	push 0
	push 68
	jmp trap_handler
vector69:
	push 0
	push 69
	jmp trap_handler
vector70:
	push 0
	push 70
	jmp trap_handler
vector71:
	push 0
	push 71
	jmp trap_handler
vector72:
	push 0
	push 72
	jmp trap_handler
vector73:
	push 0
	push 73
	jmp trap_handler
vector74:
	push 0
	push 74
	jmp trap_handler
vector75:
	push 0
	push 75
	jmp trap_handler
vector76:
	push 0
	push 76
	jmp trap_handler
vector77:
	push 0
	push 77
	jmp trap_handler
vector78:
	push 0
	push 78
	jmp trap_handler
vector79:
	push 0
	push 79
	jmp trap_handler
vector80:
	push 0
	push 80
	jmp trap_handler
vector81:
	push 0
	push 81
	jmp trap_handler
vector82:
	push 0
	push 82
	jmp trap_handler
vector83:
	push 0
	push 83
	jmp trap_handler
vector84:
	push 0
	push 84
	jmp trap_handler
vector85:
	push 0
	push 85
	jmp trap_handler
vector86:
	push 0
	push 86
	jmp trap_handler
vector87:
	push 0
	push 87
	jmp trap_handler
vector88:
	push 0
	push 88
	jmp trap_handler
vector89:
	push 0
	push 89
	jmp trap_handler
vector90:
	push 0
	push 90
	jmp trap_handler
vector91:
	push 0
	push 91
	jmp trap_handler
vector92:
	push 0
	push 92
	jmp trap_handler
vector93:
	push 0
	push 93
	jmp trap_handler
vector94:
	push 0
	push 94
	jmp trap_handler
vector95:
	push 0
	push 95
	jmp trap_handler
vector96:
	push 0
	push 96
	jmp trap_handler
vector97:
	push 0
	push 97
	jmp trap_handler
vector98:
	push 0
	push 98
	jmp trap_handler
vector99:
	push 0
	push 99
	jmp trap_handler
vector100:
	push 0
	push 100
	jmp trap_handler
vector101:
	push 0
	push 101
	jmp trap_handler
vector102:
	push 0
	push 102
	jmp trap_handler
vector103:
	push 0
	push 103
	jmp trap_handler
vector104:
	push 0
	push 104
	jmp trap_handler
vector105:
	push 0
	push 105
	jmp trap_handler
vector106:
	push 0
	push 106
	jmp trap_handler
vector107:
	push 0
	push 107
	jmp trap_handler
vector108:
	push 0
	push 108
	jmp trap_handler
vector109:
	push 0
	push 109
	jmp trap_handler
vector110:
	push 0
	push 110
	jmp trap_handler
vector111:
	push 0
	push 111
	jmp trap_handler
vector112:
	push 0
	push 112
	jmp trap_handler
vector113:
	push 0
	push 113
	jmp trap_handler
vector114:
	push 0
	push 114
	jmp trap_handler
vector115:
	push 0
	push 115
	jmp trap_handler
vector116:
	push 0
	push 116
	jmp trap_handler
vector117:
	push 0
	push 117
	jmp trap_handler
vector118:
	push 0
	push 118
	jmp trap_handler
vector119:
	push 0
	push 119
	jmp trap_handler
vector120:
	push 0
	push 120
	jmp trap_handler
vector121:
	push 0
	push 121
	jmp trap_handler
vector122:
	push 0
	push 122
	jmp trap_handler
vector123:
	push 0
	push 123
	jmp trap_handler
vector124:
	push 0
	push 124
	jmp trap_handler
vector125:
	push 0
	push 125
	jmp trap_handler
vector126:
	push 0
	push 126
	jmp trap_handler
vector127:
	push 0
	push 127
	jmp trap_handler
vector128:
	push 0
	push 128
	jmp trap_handler
vector129:
	push 0
	push 129
	jmp trap_handler
vector130:
	push 0
	push 130
	jmp trap_handler
vector131:
	push 0
	push 131
	jmp trap_handler
vector132:
	push 0
	push 132
	jmp trap_handler
vector133:
	push 0
	push 133
	jmp trap_handler
vector134:
	push 0
	push 134
	jmp trap_handler
vector135:
	push 0
	push 135
	jmp trap_handler
vector136:
	push 0
	push 136
	jmp trap_handler
vector137:
	push 0
	push 137
	jmp trap_handler
vector138:
	push 0
	push 138
	jmp trap_handler
vector139:
	push 0
	push 139
	jmp trap_handler
vector140:
	push 0
	push 140
	jmp trap_handler
vector141:
	push 0
	push 141
	jmp trap_handler
vector142:
	push 0
	push 142
	jmp trap_handler
vector143:
	push 0
	push 143
	jmp trap_handler
vector144:
	push 0
	push 144
	jmp trap_handler
vector145:
	push 0
	push 145
	jmp trap_handler
vector146:
	push 0
	push 146
	jmp trap_handler
vector147:
	push 0
	push 147
	jmp trap_handler
vector148:
	push 0
	push 148
	jmp trap_handler
vector149:
	push 0
	push 149
	jmp trap_handler
vector150:
	push 0
	push 150
	jmp trap_handler
vector151:
	push 0
	push 151
	jmp trap_handler
vector152:
	push 0
	push 152
	jmp trap_handler
vector153:
	push 0
	push 153
	jmp trap_handler
vector154:
	push 0
	push 154
	jmp trap_handler
vector155:
	push 0
	push 155
	jmp trap_handler
vector156:
	push 0
	push 156
	jmp trap_handler
vector157:
	push 0
	push 157
	jmp trap_handler
vector158:
	push 0
	push 158
	jmp trap_handler
vector159:
	push 0
	push 159
	jmp trap_handler
vector160:
	push 0
	push 160
	jmp trap_handler
vector161:
	push 0
	push 161
	jmp trap_handler
vector162:
	push 0
	push 162
	jmp trap_handler
vector163:
	push 0
	push 163
	jmp trap_handler
vector164:
	push 0
	push 164
	jmp trap_handler
vector165:
	push 0
	push 165
	jmp trap_handler
vector166:
	push 0
	push 166
	jmp trap_handler
vector167:
	push 0
	push 167
	jmp trap_handler
vector168:
	push 0
	push 168
	jmp trap_handler
vector169:
	push 0
	push 169
	jmp trap_handler
vector170:
	push 0
	push 170
	jmp trap_handler
vector171:
	push 0
	push 171
	jmp trap_handler
vector172:
	push 0
	push 172
	jmp trap_handler
vector173:
	push 0
	push 173
	jmp trap_handler
vector174:
	push 0
	push 174
	jmp trap_handler
vector175:
	push 0
	push 175
	jmp trap_handler
vector176:
	push 0
	push 176
	jmp trap_handler
vector177:
	push 0
	push 177
	jmp trap_handler
vector178:
	push 0
	push 178
	jmp trap_handler
vector179:
	push 0
	push 179
	jmp trap_handler
vector180:
	push 0
	push 180
	jmp trap_handler
vector181:
	push 0
	push 181
	jmp trap_handler
vector182:
	push 0
	push 182
	jmp trap_handler
vector183:
	push 0
	push 183
	jmp trap_handler
vector184:
	push 0
	push 184
	jmp trap_handler
vector185:
	push 0
	push 185
	jmp trap_handler
vector186:
	push 0
	push 186
	jmp trap_handler
vector187:
	push 0
	push 187
	jmp trap_handler
vector188:
	push 0
	push 188
	jmp trap_handler
vector189:
	push 0
	push 189
	jmp trap_handler
vector190:
	push 0
	push 190
	jmp trap_handler
vector191:
	push 0
	push 191
	jmp trap_handler
vector192:
	push 0
	push 192
	jmp trap_handler
vector193:
	push 0
	push 193
	jmp trap_handler
vector194:
	push 0
	push 194
	jmp trap_handler
vector195:
	push 0
	push 195
	jmp trap_handler
vector196:
	push 0
	push 196
	jmp trap_handler
vector197:
	push 0
	push 197
	jmp trap_handler
vector198:
	push 0
	push 198
	jmp trap_handler
vector199:
	push 0
	push 199
	jmp trap_handler
vector200:
	push 0
	push 200
	jmp trap_handler
vector201:
	push 0
	push 201
	jmp trap_handler
vector202:
	push 0
	push 202
	jmp trap_handler
vector203:
	push 0
	push 203
	jmp trap_handler
vector204:
	push 0
	push 204
	jmp trap_handler
vector205:
	push 0
	push 205
	jmp trap_handler
vector206:
	push 0
	push 206
	jmp trap_handler
vector207:
	push 0
	push 207
	jmp trap_handler
vector208:
	push 0
	push 208
	jmp trap_handler
vector209:
	push 0
	push 209
	jmp trap_handler
vector210:
	push 0
	push 210
	jmp trap_handler
vector211:
	push 0
	push 211
	jmp trap_handler
vector212:
	push 0
	push 212
	jmp trap_handler
vector213:
	push 0
	push 213
	jmp trap_handler
vector214:
	push 0
	push 214
	jmp trap_handler
vector215:
	push 0
	push 215
	jmp trap_handler
vector216:
	push 0
	push 216
	jmp trap_handler
vector217:
	push 0
	push 217
	jmp trap_handler
vector218:
	push 0
	push 218
	jmp trap_handler
vector219:
	push 0
	push 219
	jmp trap_handler
vector220:
	push 0
	push 220
	jmp trap_handler
vector221:
	push 0
	push 221
	jmp trap_handler
vector222:
	push 0
	push 222
	jmp trap_handler
vector223:
	push 0
	push 223
	jmp trap_handler
vector224:
	push 0
	push 224
	jmp trap_handler
vector225:
	push 0
	push 225
	jmp trap_handler
vector226:
	push 0
	push 226
	jmp trap_handler
vector227:
	push 0
	push 227
	jmp trap_handler
vector228:
	push 0
	push 228
	jmp trap_handler
vector229:
	push 0
	push 229
	jmp trap_handler
vector230:
	push 0
	push 230
	jmp trap_handler
vector231:
	push 0
	push 231
	jmp trap_handler
vector232:
	push 0
	push 232
	jmp trap_handler
vector233:
	push 0
	push 233
	jmp trap_handler
vector234:
	push 0
	push 234
	jmp trap_handler
vector235:
	push 0
	push 235
	jmp trap_handler
vector236:
	push 0
	push 236
	jmp trap_handler
vector237:
	push 0
	push 237
	jmp trap_handler
vector238:
	push 0
	push 238
	jmp trap_handler
vector239:
	push 0
	push 239
	jmp trap_handler
vector240:
	push 0
	push 240
	jmp trap_handler
vector241:
	push 0
	push 241
	jmp trap_handler
vector242:
	push 0
	push 242
	jmp trap_handler
vector243:
	push 0
	push 243
	jmp trap_handler
vector244:
	push 0
	push 244
	jmp trap_handler
vector245:
	push 0
	push 245
	jmp trap_handler
vector246:
	push 0
	push 246
	jmp trap_handler
vector247:
	push 0
	push 247
	jmp trap_handler
vector248:
	push 0
	push 248
	jmp trap_handler
vector249:
	push 0
	push 249
	jmp trap_handler
vector250:
	push 0
	push 250
	jmp trap_handler
vector251:
	push 0
	push 251
	jmp trap_handler
vector252:
	push 0
	push 252
	jmp trap_handler
vector253:
	push 0
	push 253
	jmp trap_handler
vector254:
	push 0
	push 254
	jmp trap_handler
vector255:
	push 0
	push 255
	jmp trap_handler

vectors:
	dq vector0
	dq vector1
	dq vector2
	dq vector3
	dq vector4
	dq vector5
	dq vector6
	dq vector7
	dq vector8
	dq vector9
	dq vector10
	dq vector11
	dq vector12
	dq vector13
	dq vector14
	dq vector15
	dq vector16
	dq vector17
	dq vector18
	dq vector19
	dq vector20
	dq vector21
	dq vector22
	dq vector23
	dq vector24
	dq vector25
	dq vector26
	dq vector27
	dq vector28
	dq vector29
	dq vector30
	dq vector31
	dq vector32
	dq vector33
	dq vector34
	dq vector35
	dq vector36
	dq vector37
	dq vector38
	dq vector39
	dq vector40
	dq vector41
	dq vector42
	dq vector43
	dq vector44
	dq vector45
	dq vector46
	dq vector47
	dq vector48
	dq vector49
	dq vector50
	dq vector51
	dq vector52
	dq vector53
	dq vector54
	dq vector55
	dq vector56
	dq vector57
	dq vector58
	dq vector59
	dq vector60
	dq vector61
	dq vector62
	dq vector63
	dq vector64
	dq vector65
	dq vector66
	dq vector67
	dq vector68
	dq vector69
	dq vector70
	dq vector71
	dq vector72
	dq vector73
	dq vector74
	dq vector75
	dq vector76
	dq vector77
	dq vector78
	dq vector79
	dq vector80
	dq vector81
	dq vector82
	dq vector83
	dq vector84
	dq vector85
	dq vector86
	dq vector87
	dq vector88
	dq vector89
	dq vector90
	dq vector91
	dq vector92
	dq vector93
	dq vector94
	dq vector95
	dq vector96
	dq vector97
	dq vector98
	dq vector99
	dq vector100
	dq vector101
	dq vector102
	dq vector103
	dq vector104
	dq vector105
	dq vector106
	dq vector107
	dq vector108
	dq vector109
	dq vector110
	dq vector111
	dq vector112
	dq vector113
	dq vector114
	dq vector115
	dq vector116
	dq vector117
	dq vector118
	dq vector119
	dq vector120
	dq vector121
	dq vector122
	dq vector123
	dq vector124
	dq vector125
	dq vector126
	dq vector127
	dq vector128
	dq vector129
	dq vector130
	dq vector131
	dq vector132
	dq vector133
	dq vector134
	dq vector135
	dq vector136
	dq vector137
	dq vector138
	dq vector139
	dq vector140
	dq vector141
	dq vector142
	dq vector143
	dq vector144
	dq vector145
	dq vector146
	dq vector147
	dq vector148
	dq vector149
	dq vector150
	dq vector151
	dq vector152
	dq vector153
	dq vector154
	dq vector155
	dq vector156
	dq vector157
	dq vector158
	dq vector159
	dq vector160
	dq vector161
	dq vector162
	dq vector163
	dq vector164
	dq vector165
	dq vector166
	dq vector167
	dq vector168
	dq vector169
	dq vector170
	dq vector171
	dq vector172
	dq vector173
	dq vector174
	dq vector175
	dq vector176
	dq vector177
	dq vector178
	dq vector179
	dq vector180
	dq vector181
	dq vector182
	dq vector183
	dq vector184
	dq vector185
	dq vector186
	dq vector187
	dq vector188
	dq vector189
	dq vector190
	dq vector191
	dq vector192
	dq vector193
	dq vector194
	dq vector195
	dq vector196
	dq vector197
	dq vector198
	dq vector199
	dq vector200
	dq vector201
	dq vector202
	dq vector203
	dq vector204
	dq vector205
	dq vector206
	dq vector207
	dq vector208
	dq vector209
	dq vector210
	dq vector211
	dq vector212
	dq vector213
	dq vector214
	dq vector215
	dq vector216
	dq vector217
	dq vector218
	dq vector219
	dq vector220
	dq vector221
	dq vector222
	dq vector223
	dq vector224
	dq vector225
	dq vector226
	dq vector227
	dq vector228
	dq vector229
	dq vector230
	dq vector231
	dq vector232
	dq vector233
	dq vector234
	dq vector235
	dq vector236
	dq vector237
	dq vector238
	dq vector239
	dq vector240
	dq vector241
	dq vector242
	dq vector243
	dq vector244
	dq vector245
	dq vector246
	dq vector247
	dq vector248
	dq vector249
	dq vector250
	dq vector251
	dq vector252
	dq vector253
	dq vector254
	dq vector255
